export enum ProductSegments {
  VESTUARIO = 'VESTUARIO',
  ENXOVAL = 'ENXOVAL',
  MOVEIS = 'MOVEIS',
  PUERICULTURA_LEVE = 'PUERICULTURA_LEVE',
  PUERICULTURA_PESADA = 'PUERICULTURA_PESADA',
  SAPATOS = 'SAPATOS',
  PERFUMARIA = 'PERFUMARIA',
  ADORNOS = 'ADORNOS',
}
